// rAthena msg_athena.conf
// Configuração de Mensagens do char-server
// -----------------------
0: Noviço
1: Espadachim
2: Mago
3: Arqueiro
4: Acólito
5: Comerciante
6: Ladrão
7: Cavaleiro
8: Sacerdote
9: Bruxo
10: Ferreiro
11: Caçador
12: Assassino
13: Cruzado
14: Monge
15: Sábio
16: Ladino
17: Alquimista
18: Bardo
19: Dançarina
20: Casamento
21: Super Noviço
22: Pistoleiro
23: Ninja
24: Natal
25: Noviço Avançado
26: Espadachim Avançado
27: Mago Avançado
28: Arqueiro Avançado
29: Acólito Avançado
30: Comerciante Avançado
31: Ladrão Avançado
32: Cavaleiro Lorde
33: Sumo Sacerdote
34: Arquimago
35: Ferreiro Mestre
//35: Ferreiro Mestre //Nome IRO
36: Atirador de Elite
37: Assassino Cruzado
38: Paladino
39: Campeão
40: Professor
//40: Estudioso //Nome IRO
41: Espreitador
42: Criador
//42: Bioquímico //Nome IRO
43: Palhaço
//43: Menestrel //Nome IRO
44: Cigana
45: Bebê Noviço
46: Bebê Espadachim
47: Bebê Mago
48: Bebê Arqueiro
49: Bebê Acólito
50: Bebê Comerciante
51: Bebê Ladrão
52: Bebê Cavaleiro
53: Bebê Sacerdote
54: Bebê Bruxo
55: Bebê Ferreiro
56: Bebê Caçador
57: Bebê Assassino
58: Bebê Cruzado
59: Bebê Monge
60: Bebê Sábio
61: Bebê Ladino
62: Bebê Alquimista
63: Bebê Bardo
64: Bebê Dançarina
65: Super Bebê
66: Taekwon
67: Gladiador Estelar
68: Ligador de Almas
//79: LIVRE
//70: LIVRE
71: Verão
72: Gangsi
73: Cavaleiro da Morte
74: Colecionador das Trevas
75: Cavaleiro Rúnico
76: Feiticeiro
77: Guarda-florestal
78: Arcebispo
79: Mecânico
80: Cruz de Guilhotina
81: Guarda Real
82: Feiticeiro
83: Menestrel
//83: Maestro //Nome IRO
84: Andarilha
85: Sura
86: Genético
//86: Geneticista //Nome IRO
87: Caçador Sombrio
88: Bebê Cavaleiro Rúnico
89: Bebê Feiticeiro
90: Bebê Guarda-florestal
91: Bebê Arcebispo
92: Bebê Mecânico
93: Bebê Cruz de Guilhotina
94: Bebê Guarda Real
95: Bebê Feiticeiro
96: Bebê Menestrel
97: Bebê Andarilha
98: Bebê Sura
99: Bebê Genético
100: Bebê Caçador Sombrio
101: Super Noviço Expandido
102: Super Bebê Expandido
103: Kagerou
104: Oboro
105: Hanbok
106: Rebelde
107: Oktoberfest
108: Invocador
109: Bebê Invocador
110: Bebê Ninja
111: Bebê Kagerou
112: Bebê Oboro
113: Bebê Taekwon
114: Bebê Gladiador Estelar
115: Bebê Ligador de Almas
116: Bebê Pistoleiro
117: Bebê Rebelde
118: Imperador Estelar
119: Ceifador de Almas
120: Bebê Imperador Estelar
121: Bebê Ceifador de Almas
122: Cavaleiro Dragão
123: Mestre
124: Cruz Sombria
125: Arquimago
126: Cardeal
127: Falcão do Vento
128: Guarda Imperial
129: Biolo
130: Caçador do Abismo
131: Mestre Elemental
132: Inquisidor
133: Trovador
134: Trovador
135: Imperador Celeste
136: Asceta de Almas
137: Shinkiro
138: Shiranui
139: Vigia Noturno
140: Hiper Noviço
141: Manipulador de Espíritos

199: Classe Desconhecida

//Leilão
200: Gerente de Leilão
201: Leilão
202: Obrigado, você ganhou o leilão!.
203: Pagamento pelo seu leilão!.
204: Nenhum comprador foi encontrado para o seu leilão.
205: Leilão cancelado.
206: Leilão encerrado.
207: Vencedor do leilão.
208: Alguém fez um lance mais alto.
209: Você fez um lance mais alto.
210: Você ganhou o leilão.
211: Pagamento pelo seu leilão!.

// @accountinfo
212: Nenhum resultado encontrado para seu critério, '%s'
213: Ocorreu um erro, incomode seu administrador sobre isso.
214: Sua consulta retornou %d resultados, seja mais específico...
215: [AID: %d] %s | %s | Nível: %d/%d | %s
216: Nenhuma conta com ID '%d' foi encontrada.
217: -- Conta %d --
218: Usuário: %s | Grupo GM: %d | Estado: %d
//219: LIVRE
//220: LIVRE
221: E-mail da conta: %s | Data de nascimento: %s
222: Último IP: %s (%s)
223: Este usuário fez login %d vezes, a última vez foi em %s
224: -- Detalhes do Personagem --
225: [Slot/CID: %d/%d] %s | %s | Nível: %d/%d | %s
226: Esta conta não possui personagens.

// Conquistas
227: GM
228: Correio de Recompensa de Conquista
229: [%s] Recompensa de Conquista.