#
# Table structure for table `item_db2_re`
#

DROP TABLE IF EXISTS `item_db2_re`;
CREATE TABLE `item_db2_re` (
  `id` int(10) unsigned NOT NULL DEFAULT '0',
  `name_aegis` varchar(50) DEFAULT NULL,
  `name_english` varchar(100) DEFAULT NULL,
  `type` varchar(20) DEFAULT NULL,
  `subtype` varchar(20) DEFAULT NULL,
  `price_buy` mediumint(8) unsigned DEFAULT NULL,
  `price_sell` mediumint(8) unsigned DEFAULT NULL,
  `weight` smallint(5) unsigned DEFAULT NULL,
  `attack` smallint(5) unsigned DEFAULT NULL,
  `magic_attack` smallint(5) unsigned DEFAULT NULL,
  `defense` smallint(5) unsigned DEFAULT NULL,
  `range` tinyint(2) unsigned DEFAULT NULL,
  `slots` tinyint(2) unsigned DEFAULT NULL,
  `job_all` tinyint(1) unsigned DEFAULT NULL,
  `job_acolyte` tinyint(1) unsigned DEFAULT NULL,
  `job_alchemist` tinyint(1) unsigned DEFAULT NULL,
  `job_archer` tinyint(1) unsigned DEFAULT NULL,
  `job_assassin` tinyint(1) unsigned DEFAULT NULL,
  `job_barddancer` tinyint(1) unsigned DEFAULT NULL,
  `job_blacksmith` tinyint(1) unsigned DEFAULT NULL,
  `job_crusader` tinyint(1) unsigned DEFAULT NULL,
  `job_gunslinger` tinyint(1) unsigned DEFAULT NULL,
  `job_hunter` tinyint(1) unsigned DEFAULT NULL,
  `job_kagerouoboro` tinyint(1) unsigned DEFAULT NULL,
  `job_knight` tinyint(1) unsigned DEFAULT NULL,
  `job_mage` tinyint(1) unsigned DEFAULT NULL,
  `job_merchant` tinyint(1) unsigned DEFAULT NULL,
  `job_monk` tinyint(1) unsigned DEFAULT NULL,
  `job_ninja` tinyint(1) unsigned DEFAULT NULL,
  `job_novice` tinyint(1) unsigned DEFAULT NULL,
  `job_priest` tinyint(1) unsigned DEFAULT NULL,
  `job_rebellion` tinyint(1) unsigned DEFAULT NULL,
  `job_rogue` tinyint(1) unsigned DEFAULT NULL,
  `job_sage` tinyint(1) unsigned DEFAULT NULL,
  `job_soullinker` tinyint(1) unsigned DEFAULT NULL,
  `job_spirit_handler` tinyint(1) unsigned DEFAULT NULL,
  `job_stargladiator` tinyint(1) unsigned DEFAULT NULL,
  `job_summoner` tinyint(1) unsigned DEFAULT NULL,
  `job_supernovice` tinyint(1) unsigned DEFAULT NULL,
  `job_swordman` tinyint(1) unsigned DEFAULT NULL,
  `job_taekwon` tinyint(1) unsigned DEFAULT NULL,
  `job_thief` tinyint(1) unsigned DEFAULT NULL,
  `job_wizard` tinyint(1) unsigned DEFAULT NULL,
  `class_all` tinyint(1) unsigned DEFAULT NULL,
  `class_normal` tinyint(1) unsigned DEFAULT NULL,
  `class_upper` tinyint(1) unsigned DEFAULT NULL,
  `class_baby` tinyint(1) unsigned DEFAULT NULL,
  `class_third` tinyint(1) unsigned DEFAULT NULL,
  `class_third_upper` tinyint(1) unsigned DEFAULT NULL,
  `class_third_baby` tinyint(1) unsigned DEFAULT NULL,
  `class_fourth` tinyint(1) unsigned DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `location_head_top` tinyint(1) unsigned DEFAULT NULL,
  `location_head_mid` tinyint(1) unsigned DEFAULT NULL,
  `location_head_low` tinyint(1) unsigned DEFAULT NULL,
  `location_armor` tinyint(1) unsigned DEFAULT NULL,
  `location_right_hand` tinyint(1) unsigned DEFAULT NULL,
  `location_left_hand` tinyint(1) unsigned DEFAULT NULL,
  `location_garment` tinyint(1) unsigned DEFAULT NULL,
  `location_shoes` tinyint(1) unsigned DEFAULT NULL,
  `location_right_accessory` tinyint(1) unsigned DEFAULT NULL,
  `location_left_accessory` tinyint(1) unsigned DEFAULT NULL,
  `location_costume_head_top` tinyint(1) unsigned DEFAULT NULL,
  `location_costume_head_mid` tinyint(1) unsigned DEFAULT NULL,
  `location_costume_head_low` tinyint(1) unsigned DEFAULT NULL,
  `location_costume_garment` tinyint(1) unsigned DEFAULT NULL,
  `location_ammo` tinyint(1) unsigned DEFAULT NULL,
  `location_shadow_armor` tinyint(1) unsigned DEFAULT NULL,
  `location_shadow_weapon` tinyint(1) unsigned DEFAULT NULL,
  `location_shadow_shield` tinyint(1) unsigned DEFAULT NULL,
  `location_shadow_shoes` tinyint(1) unsigned DEFAULT NULL,
  `location_shadow_right_accessory` tinyint(1) unsigned DEFAULT NULL,
  `location_shadow_left_accessory` tinyint(1) unsigned DEFAULT NULL,
  `weapon_level` tinyint(1) unsigned DEFAULT NULL,
  `armor_level` tinyint(1) unsigned DEFAULT NULL,
  `equip_level_min` smallint unsigned DEFAULT NULL,
  `equip_level_max` smallint unsigned DEFAULT NULL,
  `refineable` tinyint(1) unsigned DEFAULT NULL,
  `gradable` tinyint(1) unsigned DEFAULT NULL,
  `view` smallint(5) unsigned DEFAULT NULL,
  `alias_name` varchar(50) DEFAULT NULL,
  `flag_buyingstore` tinyint(1) unsigned DEFAULT NULL,
  `flag_deadbranch` tinyint(1) unsigned DEFAULT NULL,
  `flag_container` tinyint(1) unsigned DEFAULT NULL,
  `flag_uniqueid` tinyint(1) unsigned DEFAULT NULL,
  `flag_bindonequip` tinyint(1) unsigned DEFAULT NULL,
  `flag_dropannounce` tinyint(1) unsigned DEFAULT NULL,
  `flag_noconsume` tinyint(1) unsigned DEFAULT NULL,
  `flag_dropeffect` varchar(20) DEFAULT NULL,
  `delay_duration` bigint(20) unsigned DEFAULT NULL,
  `delay_status` varchar(30) DEFAULT NULL,
  `stack_amount` smallint(5) unsigned DEFAULT NULL,
  `stack_inventory` tinyint(1) unsigned DEFAULT NULL,
  `stack_cart` tinyint(1) unsigned DEFAULT NULL,
  `stack_storage` tinyint(1) unsigned DEFAULT NULL,
  `stack_guildstorage` tinyint(1) unsigned DEFAULT NULL,
  `nouse_override` smallint(5) unsigned DEFAULT NULL,
  `nouse_sitting` tinyint(1) unsigned DEFAULT NULL,
  `trade_override` smallint(5) unsigned DEFAULT NULL,
  `trade_nodrop` tinyint(1) unsigned DEFAULT NULL,
  `trade_notrade` tinyint(1) unsigned DEFAULT NULL,
  `trade_tradepartner` tinyint(1) unsigned DEFAULT NULL,
  `trade_nosell` tinyint(1) unsigned DEFAULT NULL,
  `trade_nocart` tinyint(1) unsigned DEFAULT NULL,
  `trade_nostorage` tinyint(1) unsigned DEFAULT NULL,
  `trade_noguildstorage` tinyint(1) unsigned DEFAULT NULL,
  `trade_nomail` tinyint(1) unsigned DEFAULT NULL,
  `trade_noauction` tinyint(1) unsigned DEFAULT NULL,
  `script` text,
  `equip_script` text,
  `unequip_script` text,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueAegisName` (`name_aegis`)
) ENGINE=MyISAM;

REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (758,'caixaVip7','Caixa VIP 7d','Usable',99,true,true,true,true,true,true,true,true,'rentitem 601,604800;\nrentitem 840097,604800;\nif (vip_status(VIP_STATUS_ACTIVE)) {\n  message strcharinfo(0),"Você já é VIP!";\n  } else {\n      atcommand "@vip +7d "+strcharinfo(0)+"";\n  }');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (759,'caixaVip15','Caixa VIP 15d','Usable',99,true,true,true,true,true,true,true,true,'rentitem 601,1296000;\nrentitem 840097,1296000;\natcommand "@vip +15d "+strcharinfo(0)+"";');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (760,'caixaVip30','Caixa VIP 30d','Usable',99,true,true,true,true,true,true,true,true,'rentitem 601,2592000;\nrentitem 840097,2592000;\natcommand "@vip +1m "+strcharinfo(0)+"";');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840055,'smw_godlike_armor_t1','Armadura Smoke GodLike [Tier I]','Armor',true,3,50,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bAtk,40+(.@scale*1);\nbonus bMatk,40+(.@scale*1);\nbonus bMaxHPrate,3;\nbonus bAtkRate,8+((.@scale*2)/10);\nbonus bMatkRate,8+((.@scale*2)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840071,'smw_godlike_armor_t2','Armadura Smoke GodLike [Tier II]','Armor',true,3,50,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bAtk,70+(.@scale*2);\nbonus bMatk,70+(.@scale*2);\nbonus bMaxHPrate,4;\nbonus bAtkRate,12+(.@scale*(35/100));\nbonus bMatkRate,12+(.@scale*(35/100));');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840072,'smw_godlike_armor_t3','Armadura Smoke GodLike [Tier III]','Armor',true,3,50,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bAtk,100+((.@scale*25)/10);\nbonus bMatk,100+((.@scale*25)/10);\nbonus bMaxHPrate,5;\nbonus bAtkRate,18+((.@scale*5)/10);\nbonus bMatkRate,18+((.@scale*5)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`script`) VALUES (840056,'smw_godlike_mantle_t1','Manto Smoke GodLike [Tier I]','Armor',true,3,50,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bDef,60;\nbonus bMdef,60;\nbonus2 bAddRace,Class_Boss,4+((.@scale*15)/100);\nbonus bRes,((.@scale*15)/100);\nbonus bMres,((.@scale*15)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`script`) VALUES (840073,'smw_godlike_mantle_t2','Manto Smoke GodLike [Tier II]','Armor',true,3,50,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bDef,90;\nbonus bMdef,90;\nbonus2 bAddRace,Class_Boss,6+((.@scale*25)/100);\nbonus bRes,((.@scale*25)/100);\nbonus bMres,((.@scale*25)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840074,'smw_godlike_mantle_t3','Manto Smoke GodLike [Tier III]','Armor',true,3,50,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bDef,110;\nbonus bMdef,110;\nbonus2 bAddRace,Class_Boss,8+((.@scale*35)/100);\nbonus bRes,((.@scale*35)/100);\nbonus bMres,((.@scale*35)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`script`) VALUES (840057,'smw_godlike_boots_t1','Botas Smoke GodLike [Tier II]','Armor',true,3,50,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bAtk,35+(.@scale*1);\nbonus bMatk,35+(.@scale*1);\nbonus bMaxSPrate,3;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*15)/100);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*15)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840075,'smw_godlike_boots_t2','Botas Smoke GodLike [Tier II]','Armor',true,3,50,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bAtk,60+((.@scale*15)/10);\nbonus bMatk,60+((.@scale*15)/10);\nbonus bMaxSPrate,4;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*25)/100);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*25)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840076,'smw_godlike_boots_t3','Botas Smoke GodLike [Tier III]','Armor',true,3,50,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>100).@lv=100;\n.@scale=.@lv-50;\nbonus bAtk,85+(.@scale*2);\nbonus bMatk,85+(.@scale*2);\nbonus bMaxSPrate,5;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*35)/100);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*35)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840058,'smw_phoenix_armor_t1','Armadura Smoke Phoenix [Tier I]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bAtk,110+(.@scale*2);\nbonus bMatk,110+(.@scale*2);\nbonus bMaxHPrate,8;\nbonus bAtkRate,18+((.@scale*5)/10);\nbonus bMatkRate,18+((.@scale*5)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840059,'smw_phoenix_mantle_t1','Manto Smoke Phoenix [Tier I]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bDef,120+(.@scale*2);\nbonus bMdef,120+(.@scale*2);\nbonus2 bAddRace,Class_Boss,10+((.@scale*3)/10);\nbonus bRes,((.@scale*25)/100);\nbonus bMres,((.@scale*25)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840060,'smw_phoenix_boots_t1','Botas Smoke Phoenix [Tier I]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bAtk,90+(.@scale*2);\nbonus bMatk,90+(.@scale*2);\nbonus bMaxSPrate,5;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*3)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*3)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840077,'smw_phoenix_armor_t2','Armadura Smoke Phoenix [Tier II]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bAtk,150+(.@scale*3);\nbonus bMatk,150+(.@scale*3);\nbonus bMaxHPrate,10;\nbonus bAtkRate,25+((.@scale*7)/10);\nbonus bMatkRate,25+((.@scale*7)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840078,'smw_phoenix_mantle_t2','Manto Smoke Phoenix [Tier II]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bDef,150+(.@scale*3);\nbonus bMdef,150+(.@scale*3);\nbonus2 bAddRace,Class_Boss,15+((.@scale*45)/100);\nbonus bRes,((.@scale*35)/100);\nbonus bMres,((.@scale*35)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840079,'smw_phoenix_boots_t2','Botas Smoke Phoenix [Tier II]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bAtk,120+(.@scale*3);\nbonus bMatk,120+(.@scale*3);\nbonus bMaxSPrate,7;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*5)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*5)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840080,'smw_phoenix_armor_t3','Armadura Smoke Phoenix [Tier III]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bAtk,180+(.@scale*4);\nbonus bMatk,180+(.@scale*4);\nbonus bMaxHPrate,12;\nbonus bAtkRate,32+(.@scale*1);\nbonus bMatkRate,32+(.@scale*1);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840081,'smw_phoenix_mantle_t3','Manto Smoke Phoenix [Tier III]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bDef,170+(.@scale*4);\nbonus bMdef,170+(.@scale*4);\nbonus2 bAddRace,Class_Boss,18+((.@scale*6)/10);\nbonus bRes,((.@scale*45)/100);\nbonus bMres,((.@scale*45)/100);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840082,'smw_phoenix_boots_t3','Botas Smoke Phoenix [Tier III]','Armor',1,true,4,100,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>150).@lv=150;\n.@scale=.@lv-100;\nbonus bAtk,150+(.@scale*4);\nbonus bMatk,150+(.@scale*4);\nbonus bMaxSPrate,8;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*7)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*7)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840061,'smw_azur_armor_t1','Armadura Smoke Azur [Tier I]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>200).@lv=200;\n.@scale=.@lv-150;\nbonus bAtk,180+(.@scale*3);\nbonus bMatk,180+(.@scale*3);\nbonus bMaxHPrate,12;\nbonus bAtkRate,30+((.@scale*7)/10);\nbonus bMatkRate,30+((.@scale*7)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840062,'smw_azur_mantle_t1','Manto Smoke Azur [Tier I]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv > 200).@lv=200;\n.@scale=.@lv-150;\nbonus bDef,180+(.@scale*3);\nbonus bMdef,180+(.@scale*3);\nbonus2 bAddRace,Class_Boss,18+((.@scale*5)/10);\nbonus bRes,((.@scale*4)/10);\nbonus bMres,((.@scale*4)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840063,'smw_azur_boots_t1','Botas Smoke Azur [Tier I]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>200).@lv=200;\n.@scale=.@lv-150;\nbonus bAtk,150+(.@scale*3);\nbonus bMatk,150+(.@scale*3);\nbonus bMaxSPrate,7;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*5)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*5)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840083,'smw_azur_armor_t2','Armadura Smoke Azur [Tier II]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>200).@lv=200;\n.@scale=.@lv-150;\nbonus bAtk,220+(.@scale*4);\nbonus bMatk,220+(.@scale*4);\nbonus bMaxHPrate,14;\nbonus bAtkRate,40+(.@scale*1);\nbonus bMatkRate,40+(.@scale*1);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840084,'smw_azur_mantle_t2','Manto Smoke Azur [Tier II]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv > 200).@lv=200;\n.@scale=.@lv-150;\nbonus bDef,220+(.@scale*4);\nbonus bMdef,220+(.@scale*4);\nbonus2 bAddRace,Class_Boss,24+((.@scale*7)/10);\nbonus bRes,((.@scale*6)/10);\nbonus bMres,((.@scale*6)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840085,'smw_azur_boots_t2','Botas Smoke Azur [Tier II]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>200).@lv=200;\n.@scale=.@lv-150;\nbonus bAtk,180+(.@scale*4);\nbonus bMatk,180+(.@scale*4);\nbonus bMaxSPrate,9;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*7)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*7)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840086,'smw_azur_armor_t3','Armadura Smoke Azur [Tier III]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>200).@lv=200;\n.@scale=.@lv-150;\nbonus bAtk,250+(.@scale*5);\nbonus bMatk,250+(.@scale*5);\nbonus bMaxHPrate,16;\nbonus bAtkRate,48+((.@scale*13)/10);\nbonus bMatkRate,48+((.@scale*13)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840087,'smw_azur_mantle_t3','Manto Smoke Azur [Tier III]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv > 200).@lv=200;\n.@scale=.@lv-150;\nbonus bDef,250+(.@scale*5);\nbonus bMdef,250+(.@scale*5);\nbonus2 bAddRace,Class_Boss,28+((.@scale*9)/10);\nbonus bRes,((.@scale*7)/10);\nbonus bMres,((.@scale*7)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840088,'smw_azur_boots_t3','Botas Smoke Azur [Tier III]','Armor',2,true,5,150,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>200).@lv=200;\n.@scale=.@lv-150;\nbonus bAtk,200+(.@scale*5);\nbonus bMatk,200+(.@scale*5);\nbonus bMaxSPrate,10;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*9)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*9)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840064,'smw_ascension_armor_t1','Armadura Smoke Ascension [Tier I]','Armor',3,true,6,200,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bAtk,260+(.@scale*4);\nbonus bMatk,260+(.@scale*4);\nbonus bMaxHPrate,15;\nbonus bAtkRate,50+(.@scale*1);\nbonus bMatkRate,50+(.@scale*1);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840065,'smw_ascension_mantle_t1','Manto Smoke Ascension [Tier I]','Armor',3,true,6,200,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bDef,260+(.@scale*4);\nbonus bMdef,260+(.@scale*4);\nbonus2 bAddRace,Class_Boss,25+((.@scale*7)/10);\nbonus bRes,((.@scale*6)/10);\nbonus bMres,((.@scale*6)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840066,'smw_ascension_boots_t1','Botas Smoke Ascension [Tier I]','Armor',3,true,6,200,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bAtk,210+(.@scale*4);\nbonus bMatk,210+(.@scale*4);\nbonus bMaxSPrate,10;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*7)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*7)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840089,'smw_ascension_armor_t2','Armadura Smoke Ascension [Tier II]','Armor',3,true,6,200,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bAtk,310+(.@scale*6);\nbonus bMatk,310+(.@scale*6);\nbonus bMaxHPrate,18;\nbonus bAtkRate,65+((.@scale*15)/10);\nbonus bMatkRate,65+((.@scale*15)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840090,'smw_ascension_mantle_t2','Manto Smoke Ascension [Tier II]','Armor',3,true,6,200,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bDef,310+(.@scale*6);\nbonus bMdef,310+(.@scale*6);\nbonus2 bAddRace,Class_Boss,32+((.@scale*9)/10);\nbonus bRes,((.@scale*8)/10);\nbonus bMres,((.@scale*8)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840091,'smw_ascension_boots_t2','Botas Smoke Ascension [Tier II]','Armor',3,true,6,200,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bAtk,250+(.@scale*5);\nbonus bMatk,250+(.@scale*5);\nbonus bMaxSPrate,13;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*9)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*9)/10);');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_armor`,`armor_level`,`equip_level_min`,`refineable`,`gradable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840092,'smw_ascension_armor_t3','Armadura Smoke Ascension [Tier III]','Armor',3,true,6,200,true,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bAtk,350+(.@scale*7);\nbonus bMatk,350+(.@scale*7);\nbonus bMaxHPrate,20;\nbonus bAtkRate,75+((.@scale*18)/10);\nbonus bMatkRate,75+((.@scale*18)/10);\n.@g = getenchantgrade();\nif (.@g >= ENCHANTGRADE_D) {\n    bonus bAllStats,2;\n    bonus bAtkRate,3;\n    bonus bMatkRate,3;\n    if (.@g >= ENCHANTGRADE_C) {\n        bonus bAllStats,1;\n        bonus bAtkRate,1;\n        bonus bMatkRate,1;\n        if (.@g >= ENCHANTGRADE_B) {\n            bonus bAllStats,1;\n            bonus bAtkRate,1;\n            bonus bMatkRate,1;\n            if (.@g >= ENCHANTGRADE_A) {\n                bonus bAllStats,2;\n                bonus bAtkRate,2;\n                bonus bMatkRate,2;\n            }\n        }\n    }\n}');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_garment`,`armor_level`,`equip_level_min`,`refineable`,`gradable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840093,'smw_ascension_mantle_t3','Manto Smoke Ascension [Tier III]','Armor',3,true,6,200,true,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bDef,350+(.@scale*7);\nbonus bMdef,350+(.@scale*7);\nbonus2 bAddRace,Class_Boss,38+((.@scale*11)/10);\nbonus bRes,((.@scale*9)/10);\nbonus bMres,((.@scale*9)/10);\n.@g = getenchantgrade();\nif (.@g >= ENCHANTGRADE_D) {\n    bonus bAspdRate,2;\n    bonus bVariableCastrate,-4;\n    if (.@g >= ENCHANTGRADE_C) {\n        bonus bAspdRate,1;\n        bonus bVariableCastrate,-2;\n        bonus bFixedCastrate,-2;\n        if (.@g >= ENCHANTGRADE_B) {\n            bonus bAspdRate,1;\n            bonus bVariableCastrate,-2;\n            bonus bFixedCastrate,-2;\n            if (.@g >= ENCHANTGRADE_A) {\n                bonus bAspdRate,1;\n                bonus bVariableCastrate,-2;\n                bonus bFixedCastrate,-3;\n            }\n        }\n    }\n}');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`slots`,`location_shoes`,`armor_level`,`equip_level_min`,`refineable`,`gradable`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840094,'smw_ascension_boots_t3','Botas Smoke Ascension [Tier III]','Armor',3,true,6,200,true,true,99,true,true,true,true,true,true,true,true,'.@lv=BaseLevel;\nif(.@lv>250).@lv=250;\n.@scale=.@lv-200;\nbonus bAtk,280+(.@scale*6);\nbonus bMatk,280+(.@scale*6);\nbonus bMaxSPrate,13;\nbonus2 bIgnoreDefClassRate,Class_All,((.@scale*11)/10);\nbonus2 bIgnoreMdefClassRate,Class_All,((.@scale*11)/10);\n.@g = getenchantgrade();\nif (.@g >= ENCHANTGRADE_D) {\n    bonus bAllStats,2;\n    bonus bMaxHPrate,4;\n    bonus bMaxSPrate,4;\n    if (.@g >= ENCHANTGRADE_C) {\n        bonus bAllStats,1;\n        bonus bMaxHPrate,2;\n        bonus bMaxSPrate,2;\n        if (.@g >= ENCHANTGRADE_B) {\n            bonus bAllStats,1;\n            bonus bMaxHPrate,2;\n            bonus bMaxSPrate,2;\n            if (.@g >= ENCHANTGRADE_A) {\n                bonus bAllStats,2;\n                bonus bMaxHPrate,2;\n                bonus bMaxSPrate,2;\n            }\n        }\n    }\n}');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840067,'smk_container_godlike','Container Smoke GodLike','Usable',99,true,true,true,true,true,true,true,true,'getitembound 840055,1,Bound_Char;\ngetitembound 840056,1,Bound_Char;\ngetitembound 840057,1,Bound_Char;\nspecialeffect2 EF_BEGINSPELL_N5;\nmessage strcharinfo(0),"!!Poder Smoke GodLike Despertado!!";\nannounce "O jogador ["+strcharinfo(0)+"] despertou o poder da Smoke GodLike!",bc_all,0xFFFF00;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840068,'smk_container_phoenix','Container Smoke Phoenix','Usable',99,true,true,true,true,true,true,true,true,'getitembound 840058,1,Bound_Char;\ngetitembound 840059,1,Bound_Char;\ngetitembound 840060,1,Bound_Char;\nspecialeffect2 EF_BEGINSPELL_N3;\nmessage strcharinfo(0),"!!Poder Smoke Phoenix Despertado!!";\nannounce "O jogador ["+strcharinfo(0)+"] despertou o poder da Smoke Phoenix!",bc_all,0xFF3300;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840069,'smk_container_azur','Container Smoke Azur','Usable',99,true,true,true,true,true,true,true,true,'getitembound 840061,1,Bound_Char;\ngetitembound 840062,1,Bound_Char;\ngetitembound 840063,1,Bound_Char;\nspecialeffect2 EF_BEGINSPELL_N8;\nmessage strcharinfo(0),"!!Poder Smoke Azur Despertado!!";\nannounce "O jogador ["+strcharinfo(0)+"] despertou o poder da Smoke Azur!",bc_all,0x3399FF;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840070,'smk_container_ascension','Container Smoke Ascension','Usable',99,true,true,true,true,true,true,true,true,'getitembound 840064,1,Bound_Char;\ngetitembound 840065,1,Bound_Char;\ngetitembound 840066,1,Bound_Char;\nspecialeffect2 EF_BEGINSPELL_N7;\nmessage strcharinfo(0),"!!Poder Smoke Ascension Despertado!!";\nannounce "O jogador ["+strcharinfo(0)+"] despertou o poder da Smoke Ascension!",bc_all,0x9900FF;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_noconsume`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840099,'smk_hammer_divine','Martelo dos Deuses','Usable',10,true,99,true,true,true,true,true,true,true,true,'if(countitem(840100)>0) { item_reform(); }');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840100,'smk_anvil_divine','Fornalha Divina','Etc',10,99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840103,'smw_rune_frag_life','Fragmento de Runa da Vida','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840104,'smw_rune_frag_fire','Fragmento de Runa do Fogo','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840105,'smw_rune_frag_ice','Fragmento de Runa do Gelo','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840106,'smw_rune_frag_death','Fragmento de Runa da Morte','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840107,'smw_rune_frag_ancestral','Fragmento de Runa Ancestral','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840108,'smw_rune_frag_divine','Fragmento de Runa Divina','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840109,'smw_rune_life','Runa da Vida','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840110,'smw_rune_fire','Runa do Fogo','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840111,'smw_rune_ice','Runa do Gelo','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840112,'smw_rune_death','Runa da Morte','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840113,'smw_rune_ancestral','Runa Ancestral','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840114,'smw_rune_divine','Runa Divina','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840115,'smw_rune_essence_life','Essência da Vida','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840116,'smw_rune_essence_fire','Essência do Fogo','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840117,'smw_rune_essence_ice','Essência do Gelo','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840118,'smw_rune_essence_death','Essência da Morte','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840119,'smw_rune_essence_ancestral','Essência Ancestral','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840120,'smw_rune_essence_divine','Essência Divina','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`,`script`) VALUES (840095,'nossaCoin','Nossa Coin','Usable','CLIENT','callfunc "addNossaCoin",1;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Mid`,`armor_level`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840047,'randoserublue','Costume Mochilinha Azul','Armor',true,1,2710,100,true,true,true,true,true,true,true,true,'bonus bAddMaxWeight,1000;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Mid`,`armor_level`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840048,'randoserugreen','Costume Mochilinha Verde','Armor',true,1,2711,100,true,true,true,true,true,true,true,true,'bonus bAddMaxWeight,1000;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Mid`,`armor_level`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840049,'randoserured','Costume Mochilinha Vermelha','Armor',true,1,2712,100,true,true,true,true,true,true,true,true,'bonus bAddMaxWeight,1000;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Mid`,`armor_level`,`view`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840050,'randoseruyellow','Costume Mochilinha Amarela','Armor',true,1,2713,100,true,true,true,true,true,true,true,true,'bonus bAddMaxWeight,1000;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`script`) VALUES (840096,'smk_check_zeny_1m','Cheque - 1M de Zeny','Usable','Zeny +=1000000;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840121,'smk_aura_red','Costume Smoke Aura Red','Armor',true,1,1,2714);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840122,'smk_aura_blue','Costume Smoke Aura Blue','Armor',true,1,1,2715);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840123,'smk_aura_cyan','Costume Smoke Aura Cyan','Armor',true,1,1,2716);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840124,'smk_aura_green','Costume Smoke Aura Green','Armor',true,1,1,2717);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840125,'smk_aura_violet','Costume Smoke Aura Violet','Armor',true,1,1,2718);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840126,'smk_aura_lilac','Costume Smoke Aura Lilac','Armor',true,1,1,2719);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840127,'smk_aura_orange','Costume Smoke Aura Orange','Armor',true,1,1,2720);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840128,'smk_aura_white','Costume Smoke Aura White','Armor',true,1,1,2721);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`location_costume_head_Low`,`armor_level`,`equip_level_min`,`view`) VALUES (840129,'smk_aura_black','Costume Smoke Aura Black','Armor',true,1,1,2722);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`delay_duration`,`delay_status`,`script`) VALUES (840097,'smk_vapor_fruit','Vapor Fruit','Healing',300,5000,'Reuse_Limit_F','itemheal 100,100;\nhealap 200;\nspecialeffect2 312;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840098,'smk_vapor_fruit2','Vapor Fruit Box','Usable',100,'getitem 840097,10;');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`) VALUES (840130,'smw_rune_frag_primo','Fragmento de Runa Primordial','Etc','CLIENT');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840132,'smw_rune_primo','Runa Primordial','Etc',10,'CLIENT',99,true,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840133,'smw_rune_essence_primo','Essência Primordial','DelayConsume',10,'laphine_synthesis();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840134,'smk_container_runes','Container Smoke GodLike','Usable','CLIENT',99,true,true,true,true,true,true,true,true,'callfunc "F_SmokeRunes";');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840135,'smk_container_frontier','Container Armas Frontier','Usable','CLIENT',99,true,true,true,true,true,true,true,true,'callfunc "caixaArmasFrontier";');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840136,'smk_rune_ansuz','Runa Frontier Ansuz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840137,'smk_rune_berkano','Runa Frontier Berkano','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840138,'smk_rune_dagaz','Runa Frontier Dagaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840139,'smk_rune_ehwaz','Runa Frontier Ehwaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840140,'smk_rune_eihaz','Runa Frontier Eihaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840141,'smk_rune_fehu','Runa Frontier Fehu','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840142,'smk_rune_gebo','Runa Frontier Gebo','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840143,'smk_rune_hagalaz','Runa Frontier Hagalaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840144,'smk_rune_isa','Runa Frontier Isa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840145,'smk_rune_jara','Runa Frontier Jara','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840146,'smk_rune_kenaz','Runa Frontier Kenaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840147,'smk_rune_laguz','Runa Frontier Laguz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840148,'smk_rune_mannaz','Runa Frontier Mannaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840149,'smk_rune_naudhiz','Runa Frontier Naudhiz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840150,'smk_rune_othel','Runa Frontier Othel','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840151,'smk_rune_perthro','Runa Frontier Perthro','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840152,'smk_rune_raidho','Runa Frontier Raidho','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840153,'smk_rune_sowilo','Runa Frontier Sowilo','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840154,'smk_rune_thurisaz','Runa Frontier Thurisaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840155,'smk_rune_tiwaz','Runa Frontier Tiwaz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840156,'smk_rune_uraz','Runa Frontier Uraz','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nosell`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840157,'smk_rune_wunjo','Runa Frontier Wunjo','Etc',0,99,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840158,'smk_frontier_essentia','Essentia Frontier','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840159,'smk_frontier_conflux','Conflux Frontier','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840160,'smk_frontier_core','Core Frontier','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840161,'smk_frontier_aether','Aether Frontier','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840162,'SMK_ASCENSION_F','Aprimoramento Smoke Físico','DelayConsume',10,'laphine_upgrade();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`script`) VALUES (840163,'SMK_ASCENSION_M','Aprimoramento Smoke Mágico','DelayConsume',10,'laphine_upgrade();');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`script`) VALUES (840164,'smk_container_f_runes','Container Runas Frontier','Usable','callfunc "caixaRunasFrontier";');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840165,'smk_frontier_c_ansuz','Runa Frontier Ansuz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840166,'smk_frontier_c_berkano','Runa Frontier Berkano Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840167,'smk_frontier_c_dagaz','Runa Frontier Dagaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840168,'smk_frontier_c_ehwaz','Runa Frontier Ehwaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840169,'smk_frontier_c_eihaz','Runa Frontier Eihaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840170,'smk_frontier_c_fehu','Runa Frontier Fehu Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840171,'smk_frontier_c_gebo','Runa Frontier Gebo Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840172,'smk_frontier_c_hagalaz','Runa Frontier Hagalaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840173,'smk_frontier_c_isa','Runa Frontier Isa Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840174,'smk_frontier_c_jara','Runa Frontier Jara Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840175,'smk_frontier_c_kenaz','Runa Frontier Kenaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840176,'smk_frontier_c_laguz','Runa Frontier Laguz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840177,'smk_frontier_c_mannaz','Runa Frontier Mannaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840178,'smk_frontier_c_naudhiz','Runa Frontier Naudhiz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840179,'smk_frontier_c_othel','Runa Frontier Othel Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840180,'smk_frontier_c_perthro','Runa Frontier Perthro Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840181,'smk_frontier_c_raidho','Runa Frontier Raidho Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840182,'smk_frontier_c_sowilo','Runa Frontier Sowilo Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840183,'smk_frontier_c_thurisaz','Runa Frontier Thurisaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840184,'smk_frontier_c_tiwaz','Runa Frontier Tiwaz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840185,'smk_frontier_c_uraz','Runa Frontier Uraz Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nosell`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`) VALUES (840186,'smk_frontier_c_wunjo','Runa Frontier Wunjo Coroa','Etc',0,99,true,true,true,true,true,true,true);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840187,'smk_frontier_c_essentia','Essentia Frontier Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840188,'smk_frontier_c_conflux','Conflux Frontier Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840189,'smk_frontier_c_core','Core Frontier Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`weight`) VALUES (840190,'smk_frontier_c_aether','Aether Frontier Coroa','Etc',1);
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`script`) VALUES (840191,'smk_container_c_runes','Container Runas Frontier Coroa','Usable','callfunc "caixaRunasCoroasFrontier";');
REPLACE INTO `item_db2_re` (`id`,`name_aegis`,`name_english`,`type`,`flag_dropeffect`,`trade_override`,`trade_nodrop`,`trade_notrade`,`trade_tradepartner`,`trade_nocart`,`trade_nostorage`,`trade_noguildstorage`,`trade_nomail`,`trade_noauction`,`script`) VALUES (840192,'smk_container_c_frontier','Container Coroas Frontier','Usable','CLIENT',99,true,true,true,true,true,true,true,true,'callfunc "caixaCoroasFrontier";');
